dependencies:
- name: account
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.19
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- name: m360
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- alias: db1
  name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 5.3.0
- alias: fecache
  name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 5.3.0
