dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- name: m360
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.11
- alias: fecache
  name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 5.3.0
